config/routes.rb
# frozen_string_literal: true

# == Route Map
#
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :professionals
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'
  post 'ajax', to: 'home#ajax'

  resources :projects, only: %i[new show create index] do
    collection do
      get 'public'
      get 'search'
    end
    member do
      post :closed
      get :team
    end
    resources :proposals, only: %i[create show index], shallow: true do
      member do
        get :approval
        post :approval
        post :accepted
        get :refused
        post :refused
        post :cancel
      end
    end
  end

  resources :professionals do
    resources :profiles, only: %i[new create show], shallow: true do
      resources :formations, only: %i[new create], shallow: true
      resources :experiences, only: %i[new create], shallow: true
    end
  end

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show]
    end
  end
  scope ':name', as: 'professional' do
    get 'my_projects', to: 'professionals/projects#index', as: :projects
    get ':title', to: 'professionals/projects#show', as: :project
  end
end

app/views/shared/_form_proposal.html.erb
<div class="py-5 px-10 bg-white mx-auto w-4/5 space-y-1">
  <h1 class="text-2xl font-bold text-center mb-5">Formulario de submissão de proposta</h1>
  <%= form_with model: @proposal, url: project_proposals_path(@project) do |pl|%>
    <div class="my-2">
      <%= pl.label :justification, class: "font-semibold font-lg block" %>
      <%= pl.text_area :justification, placeholder: "Escreva sua justificativa aqui...", cols: 45, rows: 5 ,
                                       class: "w-1/2 ml-20 p-2 bg-gray-50 border border-black rounded-lg" %>
      <% @proposal.errors.full_messages_for(:justification).each do |erro| %>
        <span class="block"> <%= erro %> </span>
       <% end %>
    </div>

    <div class="my-2">
      <%= pl.label :price_hour, "Valor/Hora", class: "font-semibold font-lg block" %>
      <%= pl.number_field :price_hour, class: "w-1/2 ml-20 border-b border-gray-500" %>
      <% @proposal.errors.full_messages_for(:price_hour).each do |erro| %>
        <span class="block"> <%= erro %> </span>
       <% end %>
    </div>

    <div class="my-2">
      <%= pl.label :weekly_hour, class: "font-semibold font-lg block" %>
      <%= pl.number_field :weekly_hour, class: "w-1/2 ml-20 border-b border-gray-500" %>
      <% @proposal.errors.full_messages_for(:weekly_hour).each do |erro| %>
        <span class="block"> <%= erro %> </span>
       <% end %>
    </div>

    <div class="my-2">
      <%= pl.label :completion_deadline, class: "font-semibold font-lg block" %>
      <%= pl.number_field :completion_deadline, step: 1, min: 1, class: "w-1/2 ml-20 border-b border-gray-500" %>
      <% @proposal.errors.full_messages_for(:completion_deadline).each do |erro| %>
        <span class="block"> <%= erro %> </span>
       <% end %>
    </div>

    <div class="my-4">
      <%= pl.submit "Enviar", class: "bg-gray-200 py-2 px-4 border border-gray-500 rounded"%>
    </div>
  <% end %>
</div>

app/views/shared/_listen_project.html.erb
<% @projects.each do |p| %>
  <div class="bg-white rounded-t mx-auto shadow-lg w-4/6 my-2">
    <div class="bg-blue-500 rounded-t px-5 py-1 items-center text-white space-x-1">
      <%= link_to p.title, project_path(p), class: "font-bold text-2xl inline-flex"%>
      <em class="inline-flex"> <%= p.days_remaining %> dias restantes</em>
    </div>
    <div class="flex px-5 py-6">
      <div class="w-3/4">
        <dd class="px-5 font-semibold">Descrição</dd>
        <dt class="px-10"> <%= p.description %> </dt>
     </div>
     <div>
       <span class="font-semibold"><%=number_to_currency p.average_offer %></span>
       <em>média</em>
       <br>
       <span> Ofertas <%= p.proposals.size %> </span>
     </div>
    </div>
 </div>
<% end %> 

app/views/shared/_nav_bar.html.erb
<nav class="bg-white px-5 border-b-2 boder-gray-900 shadow-md py-2">
  <div class="flex justify-between container mx-auto">
          <div class="flex space-x-7">
              <div>
                  <a href="#" class="flex items-center py-4 px-2">
                    <span class="font-semibold text-black text-lg">FreelancersTECH</span>
                  </a>
              </div>

              <ul class="hidden md:flex items-center space-x-2">
                <li> <%= link_to "Home", root_path, class: "nav-text nav-link-active" %> </li>
                <li> <%= link_to "Ver Projetos", public_projects_path, class: "nav-text nav-link" %> </li>
                <%= yield :nav_bar %>
              </ul>
          </div>

          <div class="hidden md:flex items-center space-x-5 mx-5">
            <%= render "/shared/nav_link" %>
          </div>

  
  </div>
</nav>

app/views/shared/_nav_link.html.erb
<% if user_signed_in? %>
        <%= link_to 'Meus Projetos', projects_path, class: "nav-text nav-link none" %>
        <%= link_to 'Novo Projeto', new_project_path, class: "nav-text nav-link none" %>
        <div class="dropdown">
        <button id="b-drop"href="" 
                   class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-blue-600 hover:ring-4 hover:ring-indigo-300 hover:text-white transition duration-300">
                  <%= current_user.email %>
        </button>
        <ul class="dropdown-toggle text-gray-500" id="drop">
          <%= form_with url: destroy_user_session_path, method: :delete do%>
             <li> <%= button_tag "Sair", class: "dropdown-menu-top bg-white border-l-4  hover:border-blue-500" %>
          <% end %>
        </ul>
        </div>
<% end %>
<% if professional_signed_in? %>
        <% if current_professional.profile? %>
                <%= link_to 'Meus Projetos', professional_projects_path(current_professional.profile.name), class:"nav-text nav-link none" %>
        <% end %>
        <div class="dropdown">
        <button id="b-drop"href="" 
                   class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-blue-600 hover:ring-4 hover:ring-indigo-300 hover:text-white transition duration-300">
                <% if current_professional.profile.present? %>
                  <%= current_professional.profile.name %>
                <% else %>
                <%= current_professional.email %>
                <% end %>
        </button>
        <ul class="dropdown-toggle text-gray-500" id="drop">
          <%= form_with url: destroy_professional_session_path, method: :delete do%>
            <li> <%= button_tag "Sair", class: "dropdown-menu-top bg-white border-l-4  hover:border-blue-500" %>
          <% end %>
          <% if current_professional.profile? %>
           <%= link_to "Ver Perfil", professional_profile_path(current_professional.profile) %>
          <% end %>
        </ul>
        </div>
<% end %>

<% unless user_signed_in? or professional_signed_in? %>
<div class="dropdown">
        <button id="b-drop"href="" 
                   class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-blue-600 hover:ring-4 hover:ring-indigo-300 hover:text-white transition duration-300">
                  Entrar
        </button>
        <ul class="dropdown-toggle text-gray-500" id="drop">
          <li> <%= link_to "Usuário", new_user_session_path, class: "dropdown-menu-top bg-white border-l-4  hover:border-blue-500" %> </li>
          <li> <%= link_to "FreelancerTech", new_professional_session_path, class: "dropdown-menu-botton bg-white border-l-4  hover:border-blue-500" %> </li>
        </ul>
</div>
<div class="dropdown">
        <button id="b-drop-in"href="" 
                   class="py-2 px-2 font-medium text-white bg-blue-700 rounded hover:bg-blue-600 transition duration-300">
                  Inscreva-se
        </button>
        <ul class="dropdown-toggle text-gray-500" id="drop-in">
          <li> <%= link_to "Novo Usuário", new_user_registration_path, class: "dropdown-menu-top bg-white border-l-4  hover:border-blue-500" %> </li>
          <li> <%= link_to "Novo FreelancerTech", new_professional_registration_path, class: "dropdown-menu-botton bg-white border-l-4  hover:border-blue-500" %> </li>
        </ul>
</div>

<% end %>

app/views/shared/_notification.html.erb
<div class="fixed inset-10 px-4 py-6 pointer-events-none sm:p-6 sm:items-start sm:justify-end">
  <div id="notifications" class="flex flex-col items-end justify-center">
    <% flash.each do |type, data| %>
      <%= render NotificationComponent.new(type: type, data: data) %>
    <% end %>
  </div>
</div>

app/views/shared/_search.html.erb
  <div class="container mx-auto bg-blue-500 rounded-lg p-4 w-2/3 my-5">
    <h1 class="text-center font-bold text-white text-4xl">Procure o projeto perfeito para você</label>
    <br>
  <%= form_with url: search_projects_path, method: :get do%>
      <div class="flex bg-white rounded-lg px-2 py-1 justify-between">
        <%= label_tag :query, "Busca", class:"hidden" %>
        <input name="query" id='search' value="" class="text-base text-gray-400 flex-grow outline-none px-2 " type="text" placeholder="Procure projetos" />
        <%= submit_tag 'Pesquisar', class:"bg-blue-500 text-white text-base rounded-lg px-4 py-2 font-thin hover:bg-blue-400" %>
      </div>
  <% end %>
  </div>