config/routes.rb
# frozen_string_literal: true

# == Route Map
#
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :professionals
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'
  post 'ajax', to: 'home#ajax'

  resources :projects, only: %i[new show create index] do
    collection do
      get 'public'
      get 'search'
    end
    member do
      post :closed
      get :team
    end
    resources :proposals, only: %i[create show index], shallow: true do
      member do
        get :approval
        post :approval
        post :accepted
        get :refused
        post :refused
        post :cancel
      end
    end
  end

  resources :professionals do
    resources :profiles, only: %i[new create show], shallow: true do
      resources :formations, only: %i[new create], shallow: true
      resources :experiences, only: %i[new create], shallow: true
    end
  end

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show]
    end
  end
  scope ':name', as: 'professional' do
    get 'my_projects', to: 'professionals/projects#index', as: :projects
    get ':title', to: 'professionals/projects#show', as: :project
  end
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id                  :integer          not null, primary key
#  title               :string
#  description         :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  deadline_submission :date
#  user_id             :integer          not null
#  remote              :boolean          default(FALSE)
#  max_price_per_hour  :decimal(, )
#  status              :integer          default("open")
#
class Project < ApplicationRecord
  belongs_to :user
  has_many :proposals, dependent: :destroy
  has_many :professionals, through: :proposals

  validates :title, :description, :deadline_submission, :max_price_per_hour,
            presence: true, on: :create
  validates :max_price_per_hour, numericality: { greater_than: 0 }
  validate :date_past, on: :create

  enum status: { open: 0, closed: 1, finished: 2 }

  scope :available, -> { where(status: "open") }
  scope :search, lambda { |parameter|
                   where('(title like ? OR description like ?) and
                                         status = ?', "%#{parameter}%", "%#{parameter}%", 0)
                 }

  def days_remaining
    return (deadline_submission - Date.current).to_i if Date.current.before? deadline_submission

    0
  end

  def format_max_price_per_hour
    ActiveSupport::NumberHelper.number_to_currency max_price_per_hour
  end

  def average_offer
    return 0 if proposals.average('price_hour').nil?

    proposals.average('price_hour')
  end

  def belongs_to?(resource)
    if resource.is_a? Professional
      professionals.exists? resource.id
    elsif resource.is_a? User
      user.eql? resource
    else
      false
    end
  end

  private

  def date_past
    errors.add(:deadline_submission, 'não pode está no passado') if !deadline_submission
                                                                    .nil? && deadline_submission.before?(Date.current)
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # comments here
    class ProjectsController < ActionController::API
      def index
        @project = Project.all
        render json: @project
      end

      def show
        @project = Project.find(params[:id])

        render json: @project
      end
    end
  end
end

app/controllers/professionals/projects_controller.rb
# frozen_string_literal: true

module Professionals
  # comments here
  class ProjectsController < ApplicationController
    before_action :profile_complete_professsional!, only: [:index]

    def index
      @projects = current_professional.projects
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# comments here
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create index closed]
  before_action :find_project, only: %i[team show]

  def public
    @projects = Project.available
  end

  def index
    @projects = current_user.projects
  end

  def team; end

  def show
    @proposal = Proposal.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def closed
    if closed_params
      @project = Project.find(closed_params[:id])
      @project.update!(status: 'closed')
      redirect_to projects_path, notice: 'Inscrições encerradas com sucesso'
    else
      redirect_to projects_path, alert: 'Não foi possível realizar essa operação'
    end
  end

  def search
    @projects = Project.search(search_params)
    if @projects.blank?
      @projects = Project.available
      flash[:alert] = 'Sua pesquisa não encontrou nenhum projeto correspondente'
    end

    render :public
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    { user_id: current_user.id, **params.require(:project).permit(:title, :description, :deadline_submission,
                                                                  :max_price_per_hour, :remote) }
  end

  def search_params
    params[:q].present? ? params.require(:q) : "@#{$ERROR_INFO}@"
  end

  def closed_params
    if params[:status].present?
      { status: params.require(:status), id: params.require(:id) }
    else
      false
    end
  end
end

app/views/projects/index.html.erb
<div class="container">
  
  <aside class="w-1/3 mx-auto bg-white shadow-lg rounded-lg m-3 bg-red-500">
    <% if @projects.empty? %>
      <div class="p-10 text-white text-2xl">
        <p>Ops, você ainda não cadastrou projetos na plataforma</p>
        <p class="mt-10">Cadastre seu primeiro projeto agora</p>
      </div>
      <%= link_to "Cadastrar Projeto", new_project_path, class: 'bg-gray-200 text-2xl text-center 
      block p-2 hover:bg-blue-500 hover:text-white border-t-2 border-black' %>
    <% end %>
  </aside>
  <%= render '/projects/views/user_project', object: @projects %>
  <div class="w-5/6 mx-auto p-2">
    <%= render ButtonComponent.new(text: "Voltar", padding: 2) %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container mx-auto">
  <div class="w-full lg:w-7/12 bg-white p-5 rounded-lg lg:rounded-l-none mx-auto">
<% if @project.errors.any? %>
   <ul>
      <% @project.errors.full_messages.each do |error| %>
         <li><%= error %></li>
      <% end %>
   </ul>
<% end %>

<%=form_with model: @project do |p| %>

  <%= p.label :title, class: "block mb-2 text-sm font-bold text-gray-700" %>
  <%= p.text_field :title, class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" %>

  <%= p.label :description, class: "block mb-2 text-sm font-bold text-gray-700" %>
  <%= p.text_field :description, class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" %>

  <%= p.label :remote, class: "block mb-2 text-sm font-bold text-gray-700" %>
  <%= p.check_box :remote, class: "px-3 py-2 text-sm leading-tight border" %>

  <%= p.label :max_price_per_hour, "Custo máximo por hora", class: "block mb-2 text-sm font-bold text-gray-700" %>
  <%= p.number_field :max_price_per_hour, class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" %>

  <%= p.label :deadline_submission, "Receber propostas até:", class: "block mb-2 text-sm font-bold text-gray-700" %>
  <%= p.date_field :deadline_submission, class: "w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline" %>

  <%= p.submit "Enviar", class: "w-full px-4 py-2 my-8 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700 focus:outline-none focus:shadow-outline"%>
<% end %>
</div>
</div>

app/views/projects/public.html.erb
<div class="container">
    <aside>
      <% if @projects.empty? %>
        <div class="alert alert-warning">
          <p >Ops, no momento não temos projetos abertos</p>
          <p >Tente novamente mais tarde</p>
        </div>
      <% end %>
    </aside>
  <% if professional_signed_in? %>
    <%= render 'shared/search' %>
  <% end %>
  <%= render '/shared/listen_project', object: @projects %>
  <%= link_to 'Voltar', root_path, class: "bg-blue-500 border-2 border-blue-500 text-white rounded-lg text-center px-3 py-1 w-24
             transition-colors duration-700 hover:bg-white hover:border-2 hover:border-blue-500 hover:text-gray-700" %>
</div>

app/views/projects/show.html.erb
  
<div class="items-center justify-center w-5/6 mx-auto">
        <div class="max-w-4xl  bg-white w-full rounded-lg mx-auto shadow-lg m-10">
        <div class="p-4 border-b flex">
          <div class="flex-grow">
            <h2 class="text-2xl flex">
                Perfil do projeto
            </h2>
            <p class="text-sm text-gray-500">
                Detalhes e informações. 
            </p>
          </div>
          <% if @project.belongs_to? current_user %>
            <nav class="flex-0 my-auto">
              <%= render ButtonComponent.new(text: "Ver Propostas", path: project_proposals_path(@project)) %>
            </nav>
          <% end %>
        </div>
        <div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600 flex">
                    Título
                </p>
                <p>
                  <%= @project.title %>
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                  Descrição
                </p>
                <p>
                  <%= @project.description %>
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                    Preço máximo por hora
                </p>
                <p>
                    <%= @project.format_max_price_per_hour %>
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                    Remoto
                </p>
                <p>
                  <%= @project.remote ? "Sim" : "Não" %>
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                    Prazo para submissões
                </p>
                <p>
                  <%= @project.deadline_submission %>
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4">
                <p class="text-gray-600">
                    Anuciador
                </p>
                <p>
                  <%= @project.user.email %>
                </p>
            </div>
        </div>
    </div> 
    <nav class="flex flex-wrap">
    <% if @project.belongs_to? current_professional %>
      <%= render ButtonComponent.new(text: "Visualizar Proposta", path: proposal_path(current_professional.proposal_id_of_a @project), padding: 2) %>
    <% elsif current_professional.present? %>
      <%= render '/shared/form_proposal' %>
    <% end %>
      <%= render ButtonComponent.new(text: "Voltar", padding: 2) %>
    </nav>
</div>