config/routes.rb
# frozen_string_literal: true

# == Route Map
#
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :professionals
  devise_for :users

  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'
  post 'ajax', to: 'home#ajax'

  resources :projects, only: %i[new show create index] do
    collection do
      get 'public'
      get 'search'
    end
    member do
      post :closed
      get :team
    end
    resources :proposals, only: %i[create show index], shallow: true do
      member do
        get :approval
        post :approval
        post :accepted
        get :refused
        post :refused
        post :cancel
      end
    end
  end

  resources :professionals do
    resources :profiles, only: %i[new create show], shallow: true do
      resources :formations, only: %i[new create], shallow: true
      resources :experiences, only: %i[new create], shallow: true
    end
  end

  namespace :api do
    namespace :v1 do
      resources :projects, only: %i[index show]
    end
  end
  scope ':name', as: 'professional' do
    get 'my_projects', to: 'professionals/projects#index', as: :projects
    get ':title', to: 'professionals/projects#show', as: :project
  end
end

app/models/proposal.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: proposals
#
#  id                  :integer          not null, primary key
#  justification       :text
#  price_hour          :decimal(, )
#  weekly_hour         :integer
#  completion_deadline :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  professional_id     :integer          not null
#  project_id          :integer          not null
#  status              :integer          default("pending")
#  feedback            :string
#  deadline_cancel     :date
#
class Proposal < ApplicationRecord
  belongs_to :professional
  belongs_to :project

  validates :justification, :price_hour, :weekly_hour, :completion_deadline,
            presence: true
  validates :price_hour, :weekly_hour, :completion_deadline, numericality: { only: true,
                                                                             greater_than: 0 }
  validate :presence_feedback_on_refused, :duplicate_feeedback, :presence_feedback_on_cancel,
           on: :update
  validate :block_new_proposals_if_not_open, on: :create

  enum status: { pending: 0, accepted: 1, refused: 2, cancel: 3 }
  scope :count_status, ->(parameter) { where(status: parameter).count }
  scope :available, -> { where('status<> 4 or feedback is not ?', nil) }

  before_save :deadline_for_cancel_in_accepted

  def belongs_to?(resource)
    if resource.instance_of? User
      project.user.eql? resource
    elsif resource.instance_of? Professional
      professional.eql? resource
    else
      false
    end
  end

  def feedback_for?(resource)
    if resource.instance_of? Professional
      refused? and belongs_to? resource
    elsif resource.instance_of? User
      cancel? and feedback.present? and belongs_to? resource
    else
      false
    end
  end

  def can_cancel?(resource)
    if belongs_to?(resource) && accepted?
      Date.current <= deadline_cancel
    else
      pending?
    end
  end

  def days_remaning_for_cancel
    return (deadline_cancel - Date.current).to_i if Date.current.before? deadline_cancel

    0
  end

  private

  def block_new_proposals_if_not_open
    errors.add(:project_id, 'não pode receber novas propostas') if Project.find_by(id: project_id).present? &&
                                                                   !Project.find_by(id: project_id).open?
  end

  def duplicate_feeedback
    errors.add(:feedback, 'já existe') if feedback_changed? && !feedback_in_database.nil?
  end

  def presence_feedback_on_refused
    errors.add(:feedback, 'não deve ficar em branco') if refused? &&
                                                         feedback.blank?
  end

  def presence_feedback_on_cancel
    errors.add(:feedback, 'não pode ficar em branco') if cancel? &&
                                                         status_in_database.eql?('accepted') && feedback.blank?
  end

  def deadline_for_cancel_in_accepted
    self.deadline_cancel = 3.days.from_now if status_changed? && accepted?
  end
end

app/controllers/proposals_controller.rb
# frozen_string_literal: true

# comments here
class ProposalsController < ApplicationController
  before_action :authenticate_user!, only: %i[index approval
                                              accepted refused]
  before_action :authenticate_professional!, only: [:create]
  before_action :authenticate_professional_user!, only: [:show]
  before_action :find_proposal, only: %i[accepted refused cancel approval show]

  def index
    @proposals = Project.find(params[:project_id]).proposals.available
  end

  def create
    @proposal = current_professional.proposals.build(proposal_params)
    if @proposal.save
      ProposalMailDeliverJob.perform_async(@proposal.id)
      redirect_to(proposal_path(@proposal), notice: 'Proposta enviada com sucesso!')
    else
      @project = Project.find(params[:project_id])
      render 'projects/show'
    end
  end

  def show; end

  def approval; end

  def accepted
    @proposal.update(status: 'accepted')
    respond_success proposal: @proposal, notice: 'Proposta aceita com sucesso'
  end

  def refused
    if @proposal.update(status: 'refused', feedback: feedback_params)
      respond_success proposal: @proposal, notice: 'Proposta recusada com sucesso'
      return
    end
    @proposal.status = 'pending'
    respond_to do |format|
      format.js
      format.html { render :approval }
    end
  end

  def cancel
    if @proposal.update(status: 'cancel', feedback: feedback_params)
      redirect_to(proposal_path(@proposal), notice: 'Proposta cancelada com sucesso')
      return
    end
    @proposal.status = 'accepted'
    exption_proposal
    render :show
  end

  private

  def find_proposal
    @proposal = Proposal.find(params_id)
  end

  def proposals_available(proposal)
    @proposals = proposal.project.proposals.available
  end

  def respond_success(notice:, proposal:)
    proposals_available proposal
    respond_to do |format|
      format.js { render :index, notice: notice }
      format.html { redirect_to proposal_path(@proposal), notice: notice }
    end
  end

  def proposal_params
    { project_id: params[:project_id], **params.require(:proposal)
                                               .permit(:justification, :price_hour, :weekly_hour,
                                                       :completion_deadline) }
  end

  def feedback_params
    params[:feedback].present? ? params.require(:feedback) : ''
  end

  def params_id
    params.require(:id)
  end

  def exption_proposal
    flash[:alert] = 'Não foi possível realizar essa operação'
  end
end

app/views/proposals/_cancel.html.erb
<% if @proposal.can_cancel? current_professional %>
    <div class="name">

      <% if @proposal.pending? %>
        <%= form_with url: cancel_proposal_path(@proposal), method: :post do%>
          <%= button_tag 'Cancelar Proposta' %>
      <% end %>

      <% elsif @proposal.accepted? %>
       <% if @proposal.errors.any? %>
         <% @proposal.errors.full_messages_for(:feedback).each do |error| %>
           <span><%= error %></span>
         <% end %>
       <% end %>
        <%= @proposal.days_remaning_for_cancel %>
        <%= button_tag 'Cancelar Proposta', class: "cancel items-hidden" %>

        <div class="hidden items-hidden">
          <%= form_with url: cancel_proposal_path(@proposal), method: :post do%>
            <%= label_tag :feedback, 'Feedback' %>
            <%= text_field_tag :feedback %>
            <%= button_tag 'Enviar' %>
          <% end %>
          <%= button_tag 'Cancelar', class: "hidden cancel items-hidden" %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/proposals/approval.html.erb
<div class="inset-10 items-center justify-center w-5/6 mx-auto bg-gray-100 bg-opacity-50 mt-10 h-screen py-10"
     data-controller="proposal" id="proposal-show">
        <div class="transition duration-700 max-w-4xl w-full bg-white rounded-lg mx-auto shadow-lg">
          <div class="" data-proposal-target="info">
            <%# header %>
            <div class="p-4 border-b flex">
              <div class="flex-grow">
                <h2 class="text-2xl flex">
                    Proposta
                </h2>
                <p class="text-sm text-gray-500">
                    Detalhes e informações. 
                </p>
              </div>
              <div class="flex-0">
                <button data-action="proposal#close" class="ml-6 text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:underline transition ease-in-out duration-150">
                  Fechar X
              </button>
              </div>
           </div>
           <%# body - start %>
        <div>
          <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
            <p class="text-gray-600 flex">
              Justificativa
            </p>
            <p>
              <%= @proposal.justification %>
            </p>
          </div>
          <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
            <p class="text-gray-600">
              Preço por hora
            </p>
            <p>
              <%= number_to_currency @proposal.price_hour %>/h
            </p>
          </div>
          <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
            <p class="text-gray-600">
              Horas por semana
            </p>
            <p>
              <%= @proposal.weekly_hour %> hrs
            </p>
          </div>
          <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
            <p class="text-gray-600">
              Prazo de conclusão
            </p>
            <p>
              <%= @proposal.completion_deadline %> dias
            </p>
          </div>
          <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
            <p class="text-gray-600">
              Solicitante
            </p>
            <p>
              <%= @proposal.professional.email %> 
            </p>
          </div>
          <% unless @proposal.pending?%>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4">
              <p class="text-gray-600">
                Status
              </p>
              <p>
                <%= Proposal.human_enum_name(:status, @proposal.status) %>
              </p>
            </div>
          <% end %>
          <% if @proposal.feedback_for? current_user %>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-t">
              <p class="text-gray-600">
                Feedback
              </p>
              <p>
                <%= @proposal.feedback %>  
              </p>
            </div>
          <% end %>

        </div>
     </div>
    <% if @proposal.errors.any? %>
      <% @proposal.errors.full_messages_for(:feedback).each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
    <% if @proposal.pending? and @proposal.belongs_to? current_user %>

    <div class="flex items-center justify-center" data-proposal-target="refused">

      <div  data-action="click->proposal#close">
          <%= render ButtonComponent.new(text: "Aceitar", path: accepted_proposal_path(@proposal), method: :post, color: "green", local: false) %>
      </div>

      <div class="name" data-action="click->proposal#refused">
        <%= render ButtonComponent.new(text: "Recusar", path: refused_proposal_path(@proposal), color: "red", method: :post) %>
      </div>

    </div>

     <div class="p-4 w-full overflow-hidden flex items-end" data-proposal-target="form">

       <%= form_with url: refused_proposal_path(@proposal), method: :post, local: false, id: "form-refused", class: "flex-grow pl-20 items-center", 
         data: { action: "ajax:success->proposal#replace" } do %>

        <%= label_tag :feedback, "Feedback", class: "inline-block w-full text-blueGray-600 text- font-bold mb-2" %>

        <%= text_field_tag :feedback, nil,class: "flex-grow border-2 border-gray-300 px-3 py-1 ml-8 placeholder-blueGray-300 
             text-blueGray-600 h-20 bg-white rounded text-sm focus:outline-none focus:ring 
             w-5/6 ease-linear transition-all duration-150" %>

        <%= button_tag 'Enviar', class: "flex-0 bg-blue-500 border-2 py-1 px-2 rounded-lg text-white ml-2 transition-colors duration-700
              hover:bg-white hover:text-blue-500 hover:border-2 hover:border-blue-500 focus:ring-4 focus:ring-blue-300",
              data: { action: "proposal#close" } %>

     <% end %>

      <div class="flex-2 mb-5" >

        <button data-action="proposal#close" class="ml-7 mb-10 text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:underline transition ease-in-out duration-150">
          Fechar X
        </button>

        <div data-action="click->proposal#cancel">
          <%= button_tag "Cancelar", class: "mb-1 flex-0 bg-gray-500 border-2 py-1 px-2 rounded-lg text-white ml-2 transition-colors duration-700
            hover:bg-white hover:text-gray-500 hover:border-2 hover:border-gray-500 focus:ring-4 focus:ring-gray-300" %>
          <%# <%= render ButtonComponent.new(text: "Cancelar", path: "@", color: "gray") %1> %>
        </div>

     </div>

    </div>

  <% end %>
</div> 

app/views/proposals/approval.js.erb
document.getElementById('main-div')
  .insertAdjacentHTML("afterBegin", "<%=j render ProposalComponent.new(proposal: @proposal, user: current_user) %>");
document.getElementById('notifications')
  .insertAdjacentHTML("afterBegin", "<%=j render NotificationComponent.new(type: 'notice', data: "Solcitação Processada com Sucesso!!")%>");

app/views/proposals/index.html.erb
<%= render ProposalsComponent.new(proposals: @proposals) %>

app/views/proposals/index.js.erb
document.getElementById('proposal-main').remove()
document.getElementById('main-div')
  .insertAdjacentHTML("afterBegin", "<%= j render ProposalsComponent.new(proposals: @proposals) %>"
    )
  

app/views/proposals/refused.js.erb
<% if @proposal.errors.any? %>
        document.getElementById('notifications')
    .insertAdjacentHTML("afterBegin", 
        "<%=j render NotificationComponent.new(type: 'alert', data: {
            title:"Problema encontrado durante o processo de validação",
            body: @proposal.errors.full_messages.first
        })%>");
<% else %>
    document.getElementById('proposal-main').remove()
    document.getElementById('main-div')
      .insertAdjacentHTML("afterBegin", "<%= j render ProposalsComponent.new(proposals: @proposals) %>"
        )
<% end %>

app/views/proposals/show.html.erb
<div class="items-center justify-center w-5/6 mx-auto">
        <div class="max-w-4xl  bg-white w-full rounded-lg mx-auto shadow-lg m-10">
        <div class="p-4 border-b flex">
          <div class="flex-grow">
            <h2 class="text-2xl flex">
                Proposta
            </h2>
            <p class="text-sm text-gray-500">
                Detalhes e informações. 
            </p>
          </div>
        </div>
        <div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600 flex">
                    Justificativa
                </p>
                <p>
                  <%= @proposal.justification %>
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                  Preço por hora
                </p>
                <p>
                  <%= number_to_currency @proposal.price_hour %>/h
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                  Horas por semana
                </p>
                <p>
                  <%= @proposal.weekly_hour %> hrs
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                    Prazo de conclusão
                </p>
                <p>
                  <%= @proposal.completion_deadline %> dias
                </p>
            </div>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4 border-b">
                <p class="text-gray-600">
                    Solicitante
                </p>
                <p>
                  <%= @proposal.professional.email %> 
                </p>
            </div>
            <% unless @proposal.pending?%>
            <div class="md:grid md:grid-cols-2 hover:bg-gray-50 md:space-y-0 space-y-1 p-4">
                <p class="text-gray-600">
                    Status
                </p>
                <p>
                  <%= Proposal.human_enum_name(:status, @proposal.status) %>
                </p>
            </div>
            <% end %>
        </div>
</div> 

  <% if @proposal.feedback_for? current_professional %>
    <div class="name">
      <h3>Feedback</h3>
     <%= @proposal.feedback %> 
    </div>
  <% end %>
  <%= render '/proposals/cancel', object: @proposal %>